version: '3'

services:

  dont-disturb-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: guilhermeroque/dont-disturb-service
    ports:
     - "5000:5000"
    environment:
      DB_USER: postgres
      DB_PASSWORD: password
      DB_DATABASE: users
      DB_HOST: postgres
      DB_PORT: 5432
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - postgres


  postgres:
    image: "postgres:15.2-alpine"
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/